### ISSUE TITLE
pager

### ISSUE THREAD

**Issue by gerrishons** [scalabli/quo#76]

**Comment by zal-byte** [comment]
excuse me, i have an error like this
AttributeError: 'SpinningWheel' object has no attribute 'win_chars'

![error](https://user-images.githubusercontent.com/61190912/166968578-4338de01-dfbb-4725-a4ce-e93f22bd0cc5.png)

How can i solve the problem ?

Python 3.10.4
OS : windows 10

**Comment by gerrishons** [comment]
@zal-byte hi thank you for submitting this bug!

It has been resolved.
Update quo to the latest version
`pip install -U quo`
