### ISSUE TITLE
Dialogs gives an error to start [BUG]

### ISSUE THREAD

**Issue by LBY-L** [scalabli/quo#95]
You may find a solution to your problem in the [docs](https://quo.readthedocs.io) or [issues](https://github.com/scalabli/quo/issues).

**Describe the bug**
When i use the module quo.dialog i recived a some errors using a 
template of the docs which are that:

```
Traceback (most recent call last):
  File "C:\Users\esteb\Downloads\Haciendouncliente\Launch(thanks-to-portablemc).py", line 4, in <module>
    MessageBox(
  File "C:\Users\esteb\scoop\apps\python\current\Lib\site-packages\quo\dialog.py", line 475, in MessageBox
    return _MessageBox(
           ^^^^^^^^^^^^
  File "C:\Users\esteb\scoop\apps\python\current\Lib\site-packages\quo\dialog.py", line 201, in _MessageBox
    dialog = Dialog(
             ^^^^^^^
  File "C:\Users\esteb\scoop\apps\python\current\Lib\site-packages\quo\widget\dialogs.py", line 88, in __init__
    body=Frame(
         ^^^^^^
  File "C:\Users\esteb\scoop\apps\python\current\Lib\site-packages\quo\widget\core.py", line 538, in __init__
    Label(
  File "C:\Users\esteb\scoop\apps\python\current\Lib\site-packages\quo\widget\core.py", line 388, in __init__
    FormattedTextControl(Text(text)),
                         ^^^^^^^^^^
  File "C:\Users\esteb\scoop\apps\python\current\Lib\site-packages\quo\text\html.py", line 31, in __init__
    mini = minidom.parseString(f"<html-root>{value}</html-root>")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\esteb\scoop\apps\python\current\Lib\xml\dom\minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\esteb\scoop\apps\python\current\Lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\esteb\scoop\apps\python\current\Lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 36
```
Code:
```
import subprocess
from quo.dialog import MessageBox

MessageBox(
    title='Message window',
    text='Do you want to continue?\nPress ENTER to quit.')
```

**To Reproduce**
1. Run the code up ☝️

**Expected behavior**
I belive that a some argument (i don't know which) may be crashed by a error in the loading of the dialog and the core. I don't know, but i was looking in to source code and then i found the core (I don't know if this matters) and i found that would be outdated or simply broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/93894290/234755339-b300e765-f4bd-4418-a3a9-1f84cf7e5b32.png)
![image](https://user-images.githubusercontent.com/93894290/234755421-bd9a3636-148b-45ec-8947-6ea6b8cdab2e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version [e.g. 22H2 (KB5025305)]

**Android(please complete the following information):**
 - Model [e.g. Samsung]
 - OS: [eg. Android 11]
 - App [e.g. Termux]

**Additional context**
I think is probably a problem of my computer should be my ssd that's may be no too high quality and i saw some problems to start apps and programs.

**Comment by LBY-L** [comment]
Note: I wasn't update and that runs, but now that not run

**Comment by gerrishons** [comment]
Hello, thank you for reporting this bug. It has now been fixed

`pip install quo==2023.4`

Kindly update us if it's fixed on your end so we can close this issue 😊

**Comment by LBY-L** [comment]
You're welcome

**Comment by LBY-L** [comment]
Idk if this is a problem, but I was making a program with checkboxes and then they don't show the result of clicking on the buttons only what I get is "None"

**Comment by gerrishons** [comment]
Can you paste a snippet of the code here..

**Comment by LBY-L** [comment]
For what?

**Comment by LBY-L** [comment]
i think it's all by Windows 11 because, in my Windows 10 that works perfectly

**Comment by gerrishons** [comment]
`
"""
You can use a ChoiceBox instead
"""

from quo.dialog import ChoiceBox

result = ChoiceBox(
        title="ChoiceBox example",
        text="Are you sure?",
        buttons= [
            ("Yes", True),
            ("No", False),
            ("Maybe...", None)]
        )
if result == True:
    print("It's True")

**Comment by gerrishons** [comment]
[Text User Interface](https://quo.readthedocs.io/en/latest/tui.html)

You should also check this out

**Comment by LBY-L** [comment]
Thanks

**Comment by gerrishons** [comment]
FYI : pip install the latest version

`pip install quo=2023.5`

**Comment by LBY-L** [comment]
https://user-images.githubusercontent.com/93894290/235258983-2c79de83-8294-4cbf-b9e5-32b975d8856c.mp4

**Comment by LBY-L** [comment]
that was in the last version

**Comment by LBY-L** [comment]
that was in the previous version

**Comment by LBY-L** [comment]
hope this works

**Comment by LBY-L** [comment]
here we go again

**Comment by gerrishons** [comment]
Phew! Seems buggy on Windows 11
Try this 
[Example ](https://github.com/scalabli/quo/blob/master/examples/fullscreen/click-handlers.py)

**Comment by LBY-L** [comment]
lets go that works now!, because in the previous version that doesn't works

**Comment by LBY-L** [comment]
![image](https://user-images.githubusercontent.com/93894290/235261639-6b9b3a37-52d9-411e-8c30-7265672ab97a.png)

**Comment by LBY-L** [comment]
I just gonna wait if get a error i will be make you know
